[package]
name = "picast-protocols"
version.workspace = true
edition.workspace = true

[dependencies]
picast-session = { path = "../session" }
hyper = { version = "1", features = ["server", "http1"] }
hyper-util = { version = "0.1", features = ["tokio"] }
tokio-tungstenite = "0.21"
roxmltree = "0.21"
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
anyhow.workspace = true

[dev-dependencies]
tokio = { workspace = true }
serde_json = { workspace = true }
